//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.ServicioWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gestion.ServicioWeb.Empleado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gestion.ServicioWeb.Encargado))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Empleado : Gestion.ServicioWeb.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinTareasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InicioTareasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FinTareas {
            get {
                return this.FinTareasField;
            }
            set {
                if ((this.FinTareasField.Equals(value) != true)) {
                    this.FinTareasField = value;
                    this.RaisePropertyChanged("FinTareas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InicioTareas {
            get {
                return this.InicioTareasField;
            }
            set {
                if ((this.InicioTareasField.Equals(value) != true)) {
                    this.InicioTareasField = value;
                    this.RaisePropertyChanged("InicioTareas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Encargado", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Encargado : Gestion.ServicioWeb.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Farmaceutica", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Farmaceutica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionFiscal {
            get {
                return this.DireccionFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionFiscalField, value) != true)) {
                    this.DireccionFiscalField = value;
                    this.RaisePropertyChanged("DireccionFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medicamento", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Medicamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gestion.ServicioWeb.Farmaceutica FarmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gestion.ServicioWeb.Farmaceutica Farma {
            get {
                return this.FarmaField;
            }
            set {
                if ((object.ReferenceEquals(this.FarmaField, value) != true)) {
                    this.FarmaField = value;
                    this.RaisePropertyChanged("Farma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gestion.ServicioWeb.LineaPedido[] DetallePedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gestion.ServicioWeb.Empleado EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRealizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gestion.ServicioWeb.LineaPedido[] DetallePedido {
            get {
                return this.DetallePedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallePedidoField, value) != true)) {
                    this.DetallePedidoField = value;
                    this.RaisePropertyChanged("DetallePedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionEntrega {
            get {
                return this.DireccionEntregaField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionEntregaField, value) != true)) {
                    this.DireccionEntregaField = value;
                    this.RaisePropertyChanged("DireccionEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gestion.ServicioWeb.Empleado Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRealizado {
            get {
                return this.FechaRealizadoField;
            }
            set {
                if ((this.FechaRealizadoField.Equals(value) != true)) {
                    this.FechaRealizadoField = value;
                    this.RaisePropertyChanged("FechaRealizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaPedido", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class LineaPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gestion.ServicioWeb.Medicamento MedicamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gestion.ServicioWeb.Medicamento Medicamento {
            get {
                return this.MedicamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicamentoField, value) != true)) {
                    this.MedicamentoField = value;
                    this.RaisePropertyChanged("Medicamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HorasExtras", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class HorasExtras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantMinutosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gestion.ServicioWeb.Empleado EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantMinutos {
            get {
                return this.CantMinutosField;
            }
            set {
                if ((this.CantMinutosField.Equals(value) != true)) {
                    this.CantMinutosField = value;
                    this.RaisePropertyChanged("CantMinutos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gestion.ServicioWeb.Empleado Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWeb.IServicioWebBiosFarma")]
    public interface IServicioWebBiosFarma {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/AltaU", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/AltaUResponse")]
        void AltaU(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/BajaU", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/BajaUResponse")]
        void BajaU(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ModU", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ModUResponse")]
        void ModU(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Usuario pUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/Login", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/LoginResponse")]
        Gestion.ServicioWeb.Usuario Login(string nombreUsuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/CambioPass", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/CambioPassResponse")]
        void CambioPass(Gestion.ServicioWeb.Usuario pUsuario, string passNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ConsultaU", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ConsultaUResponse")]
        Gestion.ServicioWeb.Usuario ConsultaU(Gestion.ServicioWeb.Encargado login, int pCedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/AltaF", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/AltaFResponse")]
        void AltaF(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Farmaceutica farma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/BajaF", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/BajaFResponse")]
        void BajaF(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Farmaceutica farma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ModificarF", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ModificarFResponse")]
        void ModificarF(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Farmaceutica farma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ConsultaF", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ConsultaFResponse")]
        Gestion.ServicioWeb.Farmaceutica ConsultaF(Gestion.ServicioWeb.Encargado login, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ConsultaTodasF", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ConsultaTodasFResponse")]
        Gestion.ServicioWeb.Farmaceutica ConsultaTodasF(Gestion.ServicioWeb.Encargado login, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/AltaM", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/AltaMResponse")]
        void AltaM(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Medicamento med);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/BajaM", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/BajaMResponse")]
        void BajaM(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Medicamento med);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ModificarM", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ModificarMResponse")]
        void ModificarM(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Medicamento med);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ConsultaM", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ConsultaMResponse")]
        Gestion.ServicioWeb.Medicamento ConsultaM(Gestion.ServicioWeb.Encargado login, string codigo, string nombreFarma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ListaMedXml", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ListaMedXmlResponse")]
        System.Xml.Linq.XElement ListaMedXml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ListaMedStock", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ListaMedStockResponse")]
        Gestion.ServicioWeb.Medicamento[] ListaMedStock(Gestion.ServicioWeb.Empleado login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/AltaP", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/AltaPResponse")]
        void AltaP(Gestion.ServicioWeb.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ConsultaP", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ConsultaPResponse")]
        Gestion.ServicioWeb.Pedido ConsultaP(int numPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/CambioEstado", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/CambioEstadoResponse")]
        void CambioEstado(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/ListarP", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/ListarPResponse")]
        Gestion.ServicioWeb.Pedido[] ListarP(Gestion.ServicioWeb.Encargado login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioWebBiosFarma/AgregarHorasExtras", ReplyAction="http://tempuri.org/IServicioWebBiosFarma/AgregarHorasExtrasResponse")]
        void AgregarHorasExtras(Gestion.ServicioWeb.HorasExtras pHorasExtras);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioWebBiosFarmaChannel : Gestion.ServicioWeb.IServicioWebBiosFarma, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebBiosFarmaClient : System.ServiceModel.ClientBase<Gestion.ServicioWeb.IServicioWebBiosFarma>, Gestion.ServicioWeb.IServicioWebBiosFarma {
        
        public ServicioWebBiosFarmaClient() {
        }
        
        public ServicioWebBiosFarmaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebBiosFarmaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebBiosFarmaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebBiosFarmaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AltaU(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Usuario pUsuario) {
            base.Channel.AltaU(login, pUsuario);
        }
        
        public void BajaU(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Usuario pUsuario) {
            base.Channel.BajaU(login, pUsuario);
        }
        
        public void ModU(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Usuario pUsuario) {
            base.Channel.ModU(login, pUsuario);
        }
        
        public Gestion.ServicioWeb.Usuario Login(string nombreUsuario, string pass) {
            return base.Channel.Login(nombreUsuario, pass);
        }
        
        public void CambioPass(Gestion.ServicioWeb.Usuario pUsuario, string passNuevo) {
            base.Channel.CambioPass(pUsuario, passNuevo);
        }
        
        public Gestion.ServicioWeb.Usuario ConsultaU(Gestion.ServicioWeb.Encargado login, int pCedula) {
            return base.Channel.ConsultaU(login, pCedula);
        }
        
        public void AltaF(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Farmaceutica farma) {
            base.Channel.AltaF(login, farma);
        }
        
        public void BajaF(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Farmaceutica farma) {
            base.Channel.BajaF(login, farma);
        }
        
        public void ModificarF(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Farmaceutica farma) {
            base.Channel.ModificarF(login, farma);
        }
        
        public Gestion.ServicioWeb.Farmaceutica ConsultaF(Gestion.ServicioWeb.Encargado login, string nombre) {
            return base.Channel.ConsultaF(login, nombre);
        }
        
        public Gestion.ServicioWeb.Farmaceutica ConsultaTodasF(Gestion.ServicioWeb.Encargado login, string nombre) {
            return base.Channel.ConsultaTodasF(login, nombre);
        }
        
        public void AltaM(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Medicamento med) {
            base.Channel.AltaM(login, med);
        }
        
        public void BajaM(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Medicamento med) {
            base.Channel.BajaM(login, med);
        }
        
        public void ModificarM(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Medicamento med) {
            base.Channel.ModificarM(login, med);
        }
        
        public Gestion.ServicioWeb.Medicamento ConsultaM(Gestion.ServicioWeb.Encargado login, string codigo, string nombreFarma) {
            return base.Channel.ConsultaM(login, codigo, nombreFarma);
        }
        
        public System.Xml.Linq.XElement ListaMedXml() {
            return base.Channel.ListaMedXml();
        }
        
        public Gestion.ServicioWeb.Medicamento[] ListaMedStock(Gestion.ServicioWeb.Empleado login) {
            return base.Channel.ListaMedStock(login);
        }
        
        public void AltaP(Gestion.ServicioWeb.Pedido pedido) {
            base.Channel.AltaP(pedido);
        }
        
        public Gestion.ServicioWeb.Pedido ConsultaP(int numPedido) {
            return base.Channel.ConsultaP(numPedido);
        }
        
        public void CambioEstado(Gestion.ServicioWeb.Encargado login, Gestion.ServicioWeb.Pedido pedido) {
            base.Channel.CambioEstado(login, pedido);
        }
        
        public Gestion.ServicioWeb.Pedido[] ListarP(Gestion.ServicioWeb.Encargado login) {
            return base.Channel.ListarP(login);
        }
        
        public void AgregarHorasExtras(Gestion.ServicioWeb.HorasExtras pHorasExtras) {
            base.Channel.AgregarHorasExtras(pHorasExtras);
        }
    }
}
